/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Регистрация нового пользователя */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: email
                         * @example user@example.com
                         */
                        email: string;
                        /** @example username123 */
                        username: string;
                        /** @example password123 */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Пользователь успешно зарегистрирован */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
                            token?: string;
                            user?: components["schemas"]["User"];
                        };
                    };
                };
                /** @description Ошибка валидации или пользователь уже существует */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Вход в систему */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example username123 */
                        username: string;
                        /** @example password123 */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Успешный вход */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
                            token?: string;
                            user?: components["schemas"]["User"];
                        };
                    };
                };
                /** @description Ошибка валидации */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Неверные учетные данные */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/basket": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить все курсы в корзине */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список курсов в корзине */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CourseListItem"][];
                    };
                };
                /** @description Не авторизован */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/basket/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Добавить курс в корзину */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example 1 */
                        courseId: number;
                    };
                };
            };
            responses: {
                /** @description Курс добавлен в корзину */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CourseListItem"];
                    };
                };
                /** @description Ошибка валидации или курс уже в корзине */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Не авторизован */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Курс не найден */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/basket/{courseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить курс из корзины */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID курса */
                    courseId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Курс удален из корзины */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                        };
                    };
                };
                /** @description Не авторизован */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Курс не найден в корзине */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/basket/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Очистить корзину */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Корзина очищена */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                        };
                    };
                };
                /** @description Не авторизован */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить список курсов
         * @description Для неавторизованных пользователей возвращает все курсы.
         *     Для пользователей с ролью TEACHER возвращает только курсы, где они являются создателями.
         *     Для пользователей с ролью ADMIN или USER возвращает все курсы.
         *     Можно фильтровать по категории через query параметр category.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Фильтр по категории курса */
                    category?: "ALL" | "FRONTEND" | "MOBILE" | "BACKEND" | "DESIGN";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список курсов */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CourseListItem"][];
                    };
                };
                /** @description Ошибка валидации query параметров */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить информацию о курсе по ID
         * @description Возвращает полную информацию о курсе, включая информацию о создателе
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID курса */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Информация о курсе */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CourseFullInfo"];
                    };
                };
                /** @description Курс не найден */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Удалить курс
         * @description Удалить курс может только его создатель или администратор.
         *     При удалении курса также удаляются все связанные вопросы, модули и записи в корзине/избранном.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID курса */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Курс успешно удален */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                        };
                    };
                };
                /** @description Не авторизован или нет прав на удаление */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Курс не найден */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Обновить курс
         * @description Обновить курс может только его создатель или администратор.
         *     Можно обновить любое поле курса, кроме модулей и вопросов.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID курса */
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example Обновленное название курса */
                        title?: string;
                        /**
                         * Format: uri
                         * @example https://example.com/new-image.jpg
                         */
                        image?: string;
                        /** @example Обновленное описание курса */
                        description?: string;
                        /**
                         * @example [
                         *       "Новый результат 1",
                         *       "Новый результат 2"
                         *     ]
                         */
                        result?: string[];
                        /**
                         * Format: uri
                         * @example https://example.com/new-course
                         */
                        link?: string;
                        /** @example 3999 */
                        price?: number;
                        /**
                         * @example BACKEND
                         * @enum {string}
                         */
                        category?: "ALL" | "FRONTEND" | "MOBILE" | "BACKEND" | "DESIGN";
                    };
                };
            };
            responses: {
                /** @description Курс успешно обновлен */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CourseListItem"];
                    };
                };
                /** @description Ошибка валидации */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Не авторизован или нет прав на обновление */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Курс не найден */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/courses/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать новый курс */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example Основы программирования */
                        title: string;
                        /**
                         * Format: uri
                         * @example https://example.com/image.jpg
                         */
                        image?: string;
                        /** @example Курс для начинающих программистов */
                        description?: string;
                        /**
                         * @example [
                         *       "Научитесь программировать",
                         *       "Поймете основы"
                         *     ]
                         */
                        result?: string[];
                        /**
                         * Format: uri
                         * @example https://example.com/course
                         */
                        link?: string;
                        /**
                         * @default 0
                         * @example 2999
                         */
                        price?: number;
                        /**
                         * @default ALL
                         * @example FRONTEND
                         * @enum {string}
                         */
                        category?: "ALL" | "FRONTEND" | "MOBILE" | "BACKEND" | "DESIGN";
                        /**
                         * @example [
                         *       1,
                         *       2,
                         *       3
                         *     ]
                         */
                        moduleIds?: number[];
                        /**
                         * @example [
                         *       {
                         *         "title": "Что такое переменная?",
                         *         "options": [
                         *           {
                         *             "answerName": "Именованная область памяти",
                         *             "right": true
                         *           },
                         *           {
                         *             "answerName": "Функция",
                         *             "right": false
                         *           },
                         *           {
                         *             "answerName": "Класс",
                         *             "right": false
                         *           }
                         *         ]
                         *       },
                         *       {
                         *         "title": "Какой тип данных используется для целых чисел?",
                         *         "options": [
                         *           {
                         *             "answerName": "string",
                         *             "right": false
                         *           },
                         *           {
                         *             "answerName": "number",
                         *             "right": true
                         *           },
                         *           {
                         *             "answerName": "boolean",
                         *             "right": false
                         *           }
                         *         ]
                         *       }
                         *     ]
                         */
                        questions?: {
                            /** @example Что такое переменная? */
                            title: string;
                            options: {
                                /** @example Именованная область памяти */
                                answerName: string;
                                /** @example true */
                                right: boolean;
                            }[];
                        }[];
                    };
                };
            };
            responses: {
                /** @description Курс успешно создан */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CourseListItem"];
                    };
                };
                /** @description Ошибка валидации */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Не авторизован */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить все избранные курсы */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список избранных курсов */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CourseListItem"][];
                    };
                };
                /** @description Не авторизован */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/favorites/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Добавить курс в избранное */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example 1 */
                        courseId: number;
                    };
                };
            };
            responses: {
                /** @description Курс добавлен в избранное */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CourseListItem"];
                    };
                };
                /** @description Ошибка валидации или курс уже в избранном */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Не авторизован */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Курс не найден */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/favorites/{courseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить курс из избранного */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID курса */
                    courseId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Курс удален из избранного */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                        };
                    };
                };
                /** @description Не авторизован */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Курс не найден в избранном */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/modules/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить список всех модулей
         * @description Возвращает список всех модулей, отсортированных по дате создания (новые первыми)
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список модулей */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 1 */
                            id?: number;
                            /** @example Введение в программирование */
                            title?: string;
                            /**
                             * @example [
                             *       "Урок 1",
                             *       "Урок 2",
                             *       "Урок 3"
                             *     ]
                             */
                            children?: string[];
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/modules/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать новый модуль */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example Введение в программирование */
                        title: string;
                        /**
                         * @example [
                         *       "Урок 1",
                         *       "Урок 2",
                         *       "Урок 3"
                         *     ]
                         */
                        children?: string[];
                    };
                };
            };
            responses: {
                /** @description Модуль успешно создан */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id?: number;
                            title?: string;
                            children?: string[];
                        };
                    };
                };
                /** @description Ошибка валидации */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Не авторизован */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/modules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Удалить модуль
         * @description Модуль можно удалить только если он не используется ни в одном курсе.
         *     Если модуль связан с курсами, будет возвращена ошибка конфликта.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID модуля */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Модуль успешно удален */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                        };
                    };
                };
                /** @description Не авторизован */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Модуль не найден */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Модуль используется в курсах и не может быть удален */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Обновить модуль
         * @description Обновить информацию о модуле
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID модуля */
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example Обновленное название модуля */
                        title?: string;
                        /**
                         * @example [
                         *       "Урок 1",
                         *       "Урок 2",
                         *       "Урок 3",
                         *       "Урок 4"
                         *     ]
                         */
                        children?: string[];
                    };
                };
            };
            responses: {
                /** @description Модуль успешно обновлен */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id?: number;
                            title?: string;
                            children?: string[];
                        };
                    };
                };
                /** @description Ошибка валидации */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Не авторизован */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Модуль не найден */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить информацию о текущем пользователе */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Информация о пользователе */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description Не авторизован */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/me/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Обновить информацию о текущем пользователе */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: email
                         * @example newemail@example.com
                         */
                        email?: string;
                        /** @example newusername */
                        username?: string;
                    };
                };
            };
            responses: {
                /** @description Пользователь успешно обновлен */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description Ошибка валидации или данные уже заняты */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Не авторизован */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/user/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить список всех пользователей (только для админов)
         * @description Только администраторы могут просматривать список всех пользователей.
         *     Возвращает информацию о всех пользователях системы.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список всех пользователей */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id?: number;
                            email?: string;
                            username?: string;
                            /** @enum {string} */
                            role?: "ADMIN" | "USER" | "TEACHER";
                            /** Format: date-time */
                            createdAt?: string;
                            /** Format: date-time */
                            updatedAt?: string;
                        }[];
                    };
                };
                /** @description Не авторизован или нет прав доступа */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить информацию о пользователе по ID (только для админов)
         * @description Только администраторы могут просматривать детальную информацию о пользователях.
         *     Возвращает информацию о пользователе, включая список избранных курсов.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID пользователя */
                    userId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Информация о пользователе */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id?: number;
                            email?: string;
                            username?: string;
                            /** @enum {string} */
                            role?: "ADMIN" | "USER" | "TEACHER";
                            /** Format: date-time */
                            createdAt?: string;
                            /** Format: date-time */
                            updatedAt?: string;
                            favoriteItems?: {
                                id?: number;
                                courseId?: number;
                                /** Format: date-time */
                                createdAt?: string;
                                course?: {
                                    id?: number;
                                    title?: string;
                                    image?: string | null;
                                    description?: string | null;
                                    price?: number;
                                    /** @enum {string} */
                                    category?: "ALL" | "FRONTEND" | "MOBILE" | "BACKEND" | "DESIGN";
                                    /** Format: date-time */
                                    createdAt?: string;
                                    /** Format: date-time */
                                    updatedAt?: string;
                                };
                            }[];
                        };
                    };
                };
                /** @description Не авторизован или нет прав доступа */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Пользователь не найден */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{userId}/change-role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Изменить роль пользователя (только для админов)
         * @description Только администраторы могут изменять роли пользователей.
         *     Позволяет назначить пользователю одну из ролей: ADMIN, USER, TEACHER.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID пользователя, роль которого нужно изменить */
                    userId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Новая роль для пользователя
                         * @example TEACHER
                         * @enum {string}
                         */
                        role: "ADMIN" | "USER" | "TEACHER";
                    };
                };
            };
            responses: {
                /** @description Роль пользователя успешно изменена */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id?: number;
                            email?: string;
                            username?: string;
                            /** @enum {string} */
                            role?: "ADMIN" | "USER" | "TEACHER";
                            /** Format: date-time */
                            createdAt?: string;
                            /** Format: date-time */
                            updatedAt?: string;
                        };
                    };
                };
                /** @description Ошибка валидации */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Не авторизован или нет прав доступа */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Пользователь не найден */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description Сообщение об ошибке */
            error?: string;
            details?: {
                path?: string;
                message?: string;
            }[];
        };
        User: {
            id?: number;
            email?: string;
            username?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CourseListItem: {
            id?: number;
            title?: string;
            image?: string | null;
            price?: number;
            /** @enum {string} */
            category?: "ALL" | "FRONTEND" | "MOBILE" | "BACKEND" | "DESIGN";
            modulesCount?: number;
        };
        CourseFullInfo: components["schemas"]["CourseListItem"] & {
            description?: string | null;
            result?: string[];
            link?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            modules?: {
                id?: number;
                title?: string;
                children?: string[];
            }[];
            questions?: {
                id?: number;
                title?: string;
                options?: {
                    answerName: string;
                    right: boolean;
                }[];
            }[];
            creator?: {
                id?: number;
                username?: string;
                email?: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaError = components['schemas']['Error'];
export type SchemaUser = components['schemas']['User'];
export type SchemaCourseListItem = components['schemas']['CourseListItem'];
export type SchemaCourseFullInfo = components['schemas']['CourseFullInfo'];
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
